spring:
  profiles:
    active: local
  jackson:
    serialization:
      indent-output: true
      
datasource:
 sqlite:
  driverClassName: org.sqlite.JDBC
  url: jdbc:sqlite:mydb.db

#mybatis:
  #config-location: classpath:mybatis-config.xml

#thymeleaf 를 사용하려면 아래의 조건을 넣어야 한다

thymeleaf:
 check-template-location: false

server:
  port: 8445
  context-path: /agent
  error:
    whitelabel:
      enabled:  false