spring:
  profiles:
    active: local
  jackson:
    serialization:
      indent-output: true
  thymeleaf:
    cache: false
    encoding: utf-8
    check-template-location: false
   
datasource:
 sqlite:
  driverClassName: org.sqlite.JDBC
  url: jdbc:sqlite:mydb.db

#mybatis:
  #config-location: classpath:mybatis-config.xml

#thymeleaf 를 사용하려면 아래의 조건을 넣어야 한다



server:
  port: 8445
  context-path: /
  error:
    whitelabel:
      enabled:  false